cmake_minimum_required(VERSION 3.21)

foreach(_required_var SOURCE_DIR INPUT_FILE OUTPUT_FILE VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_PRE_RELEASE VERSION_BUILD_METADATA VERSION_RELEASE_DATE TARGET_NAME PROCESSOR POINTER_MODEL RC4_INT DSO_EXTENSION DSO_SCHEME SYS_DEFINES API_DEFINES FEATURE_DEFINES DISABLED_FEATURES DISABLED_PROTOCOLS DISABLED_ALGORITHMS)
    if(NOT DEFINED ${_required_var})
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

function(_openssl_trim input output_var)
    string(ASCII 13 _openssl_cr)
    string(REPLACE "${_openssl_cr}" "" _tmp "${input}")
    string(STRIP "${_tmp}" _tmp)
    set(${output_var} "${_tmp}" PARENT_SCOPE)
endfunction()

function(_openssl_comment_escape input output_var)
    string(REPLACE "\\" "\\\\" _tmp "${input}")
    string(REPLACE "\"" "\\\"" _tmp "${_tmp}")
    set(${output_var} "${_tmp}" PARENT_SCOPE)
endfunction()

function(_openssl_get_release_date output_var)
    if(NOT VERSION_RELEASE_DATE STREQUAL "")
        set(_release_date "${VERSION_RELEASE_DATE}")
    else()
        set(_release_date "xx XXX xxxx")
    endif()
    set(${output_var} "${_release_date}" PARENT_SCOPE)
endfunction()

function(_openssl_get_full_version output_var)
    set(_full_version "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}${VERSION_PRE_RELEASE}")
    if(NOT VERSION_BUILD_METADATA STREQUAL "")
        string(APPEND _full_version "+${VERSION_BUILD_METADATA}")
    endif()
    set(${output_var} "${_full_version}" PARENT_SCOPE)
endfunction()

function(_openssl_get_config_value key output_var)
    _openssl_get_release_date(_release_date)
    _openssl_get_full_version(_full_version)

    set(_value "")
    if(key STREQUAL "major")
        set(_value "${VERSION_MAJOR}")
    elseif(key STREQUAL "minor")
        set(_value "${VERSION_MINOR}")
    elseif(key STREQUAL "patch")
        set(_value "${VERSION_PATCH}")
    elseif(key STREQUAL "prerelease")
        set(_value "${VERSION_PRE_RELEASE}")
    elseif(key STREQUAL "build_metadata")
        set(_value "${VERSION_BUILD_METADATA}")
    elseif(key STREQUAL "version")
        set(_value "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
    elseif(key STREQUAL "full_version")
        set(_value "${_full_version}")
    elseif(key STREQUAL "release_date")
        set(_value "${_release_date}")
    elseif(key STREQUAL "shlib_version")
        set(_value "${VERSION_MAJOR}")
    elseif(key STREQUAL "processor")
        set(_value "${PROCESSOR}")
    elseif(key STREQUAL "rc4_int")
        set(_value "${RC4_INT}")
    elseif(key STREQUAL "FIPSKEY")
        set(_value "0000000000000000000000000000000000000000000000000000000000000000")
    elseif(key STREQUAL "FIPS_VENDOR")
        set(_value "OpenSSL CMake bootstrap")
    endif()
    set(${output_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_openssl_stack_macros output_var nametype realtype plaintype)
    set(_text "SKM_DEFINE_STACK_OF_INTERNAL(${nametype}, ${realtype}, ${plaintype})\n")
    string(APPEND _text "#define sk_${nametype}_num(sk) OPENSSL_sk_num(ossl_check_const_${nametype}_sk_type(sk))\n")
    string(APPEND _text "#define sk_${nametype}_value(sk, idx) ((${realtype} *)OPENSSL_sk_value(ossl_check_const_${nametype}_sk_type(sk), (idx)))\n")
    string(APPEND _text "#define sk_${nametype}_new(cmp) ((STACK_OF(${nametype}) *)OPENSSL_sk_set_cmp_thunks(OPENSSL_sk_new(ossl_check_${nametype}_compfunc_type(cmp)), sk_${nametype}_cmpfunc_thunk))\n")
    string(APPEND _text "#define sk_${nametype}_new_null() ((STACK_OF(${nametype}) *)OPENSSL_sk_set_thunks(OPENSSL_sk_new_null(), sk_${nametype}_freefunc_thunk))\n")
    string(APPEND _text "#define sk_${nametype}_new_reserve(cmp, n) ((STACK_OF(${nametype}) *)OPENSSL_sk_set_cmp_thunks(OPENSSL_sk_new_reserve(ossl_check_${nametype}_compfunc_type(cmp), (n)), sk_${nametype}_cmpfunc_thunk))\n")
    string(APPEND _text "#define sk_${nametype}_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_${nametype}_sk_type(sk), (n))\n")
    string(APPEND _text "#define sk_${nametype}_free(sk) OPENSSL_sk_free(ossl_check_${nametype}_sk_type(sk))\n")
    string(APPEND _text "#define sk_${nametype}_zero(sk) OPENSSL_sk_zero(ossl_check_${nametype}_sk_type(sk))\n")
    string(APPEND _text "#define sk_${nametype}_delete(sk, i) ((${realtype} *)OPENSSL_sk_delete(ossl_check_${nametype}_sk_type(sk), (i)))\n")
    string(APPEND _text "#define sk_${nametype}_delete_ptr(sk, ptr) ((${realtype} *)OPENSSL_sk_delete_ptr(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr)))\n")
    string(APPEND _text "#define sk_${nametype}_push(sk, ptr) OPENSSL_sk_push(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr))\n")
    string(APPEND _text "#define sk_${nametype}_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr))\n")
    string(APPEND _text "#define sk_${nametype}_pop(sk) ((${realtype} *)OPENSSL_sk_pop(ossl_check_${nametype}_sk_type(sk)))\n")
    string(APPEND _text "#define sk_${nametype}_shift(sk) ((${realtype} *)OPENSSL_sk_shift(ossl_check_${nametype}_sk_type(sk)))\n")
    string(APPEND _text "#define sk_${nametype}_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_freefunc_type(freefunc))\n")
    string(APPEND _text "#define sk_${nametype}_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr), (idx))\n")
    string(APPEND _text "#define sk_${nametype}_set(sk, idx, ptr) ((${realtype} *)OPENSSL_sk_set(ossl_check_${nametype}_sk_type(sk), (idx), ossl_check_${nametype}_type(ptr)))\n")
    string(APPEND _text "#define sk_${nametype}_find(sk, ptr) OPENSSL_sk_find(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr))\n")
    string(APPEND _text "#define sk_${nametype}_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr))\n")
    string(APPEND _text "#define sk_${nametype}_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_type(ptr), pnum)\n")
    string(APPEND _text "#define sk_${nametype}_sort(sk) OPENSSL_sk_sort(ossl_check_${nametype}_sk_type(sk))\n")
    string(APPEND _text "#define sk_${nametype}_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_${nametype}_sk_type(sk))\n")
    string(APPEND _text "#define sk_${nametype}_dup(sk) ((STACK_OF(${nametype}) *)OPENSSL_sk_dup(ossl_check_const_${nametype}_sk_type(sk)))\n")
    string(APPEND _text "#define sk_${nametype}_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(${nametype}) *)OPENSSL_sk_deep_copy(ossl_check_const_${nametype}_sk_type(sk), ossl_check_${nametype}_copyfunc_type(copyfunc), ossl_check_${nametype}_freefunc_type(freefunc)))\n")
    string(APPEND _text "#define sk_${nametype}_set_cmp_func(sk, cmp) ((sk_${nametype}_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_${nametype}_sk_type(sk), ossl_check_${nametype}_compfunc_type(cmp)))")
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_lhash_macros output_var type_name)
    set(_text "DEFINE_LHASH_OF_INTERNAL(${type_name});\n")
    string(APPEND _text "#define lh_${type_name}_new(hfn, cmp) ((LHASH_OF(${type_name}) *)OPENSSL_LH_set_thunks(OPENSSL_LH_new(ossl_check_${type_name}_lh_hashfunc_type(hfn), ossl_check_${type_name}_lh_compfunc_type(cmp)), lh_${type_name}_hash_thunk, lh_${type_name}_comp_thunk, lh_${type_name}_doall_thunk, lh_${type_name}_doall_arg_thunk))\n")
    string(APPEND _text "#define lh_${type_name}_free(lh) OPENSSL_LH_free(ossl_check_${type_name}_lh_type(lh))\n")
    string(APPEND _text "#define lh_${type_name}_flush(lh) OPENSSL_LH_flush(ossl_check_${type_name}_lh_type(lh))\n")
    string(APPEND _text "#define lh_${type_name}_insert(lh, ptr) ((${type_name} *)OPENSSL_LH_insert(ossl_check_${type_name}_lh_type(lh), ossl_check_${type_name}_lh_plain_type(ptr)))\n")
    string(APPEND _text "#define lh_${type_name}_delete(lh, ptr) ((${type_name} *)OPENSSL_LH_delete(ossl_check_${type_name}_lh_type(lh), ossl_check_const_${type_name}_lh_plain_type(ptr)))\n")
    string(APPEND _text "#define lh_${type_name}_retrieve(lh, ptr) ((${type_name} *)OPENSSL_LH_retrieve(ossl_check_${type_name}_lh_type(lh), ossl_check_const_${type_name}_lh_plain_type(ptr)))\n")
    string(APPEND _text "#define lh_${type_name}_error(lh) OPENSSL_LH_error(ossl_check_${type_name}_lh_type(lh))\n")
    string(APPEND _text "#define lh_${type_name}_num_items(lh) OPENSSL_LH_num_items(ossl_check_${type_name}_lh_type(lh))\n")
    string(APPEND _text "#define lh_${type_name}_node_stats_bio(lh, out) OPENSSL_LH_node_stats_bio(ossl_check_const_${type_name}_lh_type(lh), out)\n")
    string(APPEND _text "#define lh_${type_name}_node_usage_stats_bio(lh, out) OPENSSL_LH_node_usage_stats_bio(ossl_check_const_${type_name}_lh_type(lh), out)\n")
    string(APPEND _text "#define lh_${type_name}_stats_bio(lh, out) OPENSSL_LH_stats_bio(ossl_check_const_${type_name}_lh_type(lh), out)\n")
    string(APPEND _text "#define lh_${type_name}_get_down_load(lh) OPENSSL_LH_get_down_load(ossl_check_${type_name}_lh_type(lh))\n")
    string(APPEND _text "#define lh_${type_name}_set_down_load(lh, dl) OPENSSL_LH_set_down_load(ossl_check_${type_name}_lh_type(lh), dl)\n")
    string(APPEND _text "#define lh_${type_name}_doall(lh, dfn) OPENSSL_LH_doall(ossl_check_${type_name}_lh_type(lh), ossl_check_${type_name}_lh_doallfunc_type(dfn))")
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_load_param_map)
    if(DEFINED _OPENSSL_PARAM_MAP_LOADED)
        return()
    endif()

    file(STRINGS "${SOURCE_DIR}/util/perl/OpenSSL/paramnames.pm" _param_lines)
    set(_keys)
    foreach(_line IN LISTS _param_lines)
        if(_line MATCHES "^[ \\t]*'([^']+)'[ \\t]*=>[ \\t]*([^,]+),")
            set(_name "${CMAKE_MATCH_1}")
            set(_raw_value "${CMAKE_MATCH_2}")
            _openssl_trim("${_raw_value}" _value)
            if(_value MATCHES "^\"(.*)\"$")
                set(_value "${CMAKE_MATCH_1}")
            elseif(_value MATCHES "^'(.*)'$")
                set(_value "${CMAKE_MATCH_1}")
            endif()
            list(APPEND _keys "${_name}")
            string(MAKE_C_IDENTIFIER "${_name}" _ident)
            set(_OPENSSL_PARAM_VALUE_${_ident} "${_value}" CACHE INTERNAL "")
        endif()
    endforeach()
    set(_OPENSSL_PARAM_MAP_KEYS "${_keys}" CACHE INTERNAL "")
    set(_OPENSSL_PARAM_MAP_LOADED TRUE CACHE INTERNAL "")
endfunction()

function(_openssl_param_lookup name output_var)
    _openssl_load_param_map()
    string(MAKE_C_IDENTIFIER "${name}" _ident)
    if(DEFINED _OPENSSL_PARAM_VALUE_${_ident})
        set(_value "${_OPENSSL_PARAM_VALUE_${_ident}}")
        if(_value MATCHES "^\\*(.+)$")
            _openssl_param_lookup("${CMAKE_MATCH_1}" _resolved)
            set(_value "${_resolved}")
        endif()
    else()
        message(FATAL_ERROR "Unknown OpenSSL parameter name: ${name}")
    endif()
    set(${output_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_openssl_generate_public_macros output_var)
    _openssl_load_param_map()
    set(_lines)
    foreach(_key IN LISTS _OPENSSL_PARAM_MAP_KEYS)
        string(MAKE_C_IDENTIFIER "${_key}" _ident)
        set(_value "${_OPENSSL_PARAM_VALUE_${_ident}}")
        if(_value MATCHES "^\\*(.+)$")
            list(APPEND _lines "# define ${_key} ${CMAKE_MATCH_1}")
        else()
            list(APPEND _lines "# define ${_key} \"${_value}\"")
        endif()
    endforeach()
    list(SORT _lines)
    string(JOIN "\n" _text ${_lines})
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_extract_bracket_groups input output_var)
    string(LENGTH "${input}" _input_len)
    set(_groups)
    set(_current "")
    set(_depth 0)

    if(_input_len GREATER 0)
        math(EXPR _last_index "${_input_len} - 1")
        foreach(_index RANGE 0 ${_last_index})
            string(SUBSTRING "${input}" ${_index} 1 _char)
            if(_char STREQUAL "[")
                if(_depth EQUAL 0)
                    set(_current "[")
                else()
                    string(APPEND _current "${_char}")
                endif()
                math(EXPR _depth "${_depth} + 1")
            elseif(_char STREQUAL "]")
                if(_depth GREATER 0)
                    math(EXPR _depth "${_depth} - 1")
                    string(APPEND _current "]")
                    if(_depth EQUAL 0)
                        list(APPEND _groups "${_current}")
                        set(_current "")
                    endif()
                endif()
            elseif(_depth GREATER 0)
                string(APPEND _current "${_char}")
            endif()
        endforeach()
    endif()

    set(${output_var} "${_groups}" PARENT_SCOPE)
endfunction()

function(_openssl_extract_balanced_region input start_index open_char close_char output_region output_end_index)
    string(LENGTH "${input}" _input_len)
    if(start_index LESS 0 OR start_index GREATER_EQUAL _input_len)
        set(${output_region} "" PARENT_SCOPE)
        set(${output_end_index} -1 PARENT_SCOPE)
        return()
    endif()

    set(_region "")
    set(_depth 0)
    math(EXPR _last_index "${_input_len} - 1")
    foreach(_index RANGE ${start_index} ${_last_index})
        string(SUBSTRING "${input}" ${_index} 1 _char)
        if(_char STREQUAL "${open_char}")
            math(EXPR _depth "${_depth} + 1")
        endif()
        if(_depth GREATER 0)
            string(APPEND _region "${_char}")
        endif()
        if(_char STREQUAL "${close_char}" AND _depth GREATER 0)
            math(EXPR _depth "${_depth} - 1")
            if(_depth EQUAL 0)
                set(${output_region} "${_region}" PARENT_SCOPE)
                set(${output_end_index} ${_index} PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()

    set(${output_region} "" PARENT_SCOPE)
    set(${output_end_index} -1 PARENT_SCOPE)
endfunction()

function(_openssl_split_comma_fields input output_var)
    string(LENGTH "${input}" _input_len)
    set(_fields)
    set(_current "")
    set(_in_quote FALSE)

    if(_input_len GREATER 0)
        math(EXPR _last_index "${_input_len} - 1")
        foreach(_index RANGE 0 ${_last_index})
            string(SUBSTRING "${input}" ${_index} 1 _char)
            if(_char STREQUAL "'")
                if(_in_quote)
                    set(_in_quote FALSE)
                else()
                    set(_in_quote TRUE)
                endif()
                string(APPEND _current "${_char}")
            elseif(_char STREQUAL "," AND NOT _in_quote)
                _openssl_trim("${_current}" _field)
                if(NOT _field STREQUAL "")
                    list(APPEND _fields "${_field}")
                endif()
                set(_current "")
            else()
                string(APPEND _current "${_char}")
            endif()
        endforeach()
    endif()

    _openssl_trim("${_current}" _field)
    if(NOT _field STREQUAL "")
        list(APPEND _fields "${_field}")
    endif()

    set(${output_var} "${_fields}" PARENT_SCOPE)
endfunction()

function(_openssl_unquote_token input output_var)
    _openssl_trim("${input}" _token)
    if(_token MATCHES "^'(.*)'$")
        set(_token "${CMAKE_MATCH_1}")
    endif()
    set(${output_var} "${_token}" PARENT_SCOPE)
endfunction()

function(_openssl_extract_first_quoted_string input output_var)
    string(LENGTH "${input}" _input_len)
    set(_start -1)
    set(_end -1)

    if(_input_len GREATER 0)
        math(EXPR _last_index "${_input_len} - 1")
        foreach(_index RANGE 0 ${_last_index})
            string(SUBSTRING "${input}" ${_index} 1 _char)
            if(_char STREQUAL "'")
                if(_start EQUAL -1)
                    set(_start ${_index})
                else()
                    set(_end ${_index})
                    break()
                endif()
            endif()
        endforeach()
    endif()

    if(_start GREATER -1 AND _end GREATER ${_start})
        math(EXPR _value_start "${_start} + 1")
        math(EXPR _value_len "${_end} - ${_value_start}")
        string(SUBSTRING "${input}" ${_value_start} ${_value_len} _value)
    else()
        set(_value "")
    endif()

    set(${output_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_openssl_parse_decoder_tuple tuple output_var)
    _openssl_trim("${tuple}" _tuple)
    string(REGEX REPLACE "^\\[[ \\t\\r\\n]*" "" _body "${_tuple}")
    string(REGEX REPLACE "[ \\t\\r\\n]*\\]$" "" _body "${_body}")
    _openssl_split_comma_fields("${_body}" _fields)
    list(LENGTH _fields _field_count)
    if(_field_count LESS 2)
        set(${output_var} "" PARENT_SCOPE)
        return()
    endif()

    list(GET _fields 0 _name_token)
    list(GET _fields 1 _ident_token)
    _openssl_unquote_token("${_name_token}" _name)
    _openssl_unquote_token("${_ident_token}" _ident)

    set(_type "")
    set(_count "")
    if(_field_count GREATER 2)
        list(GET _fields 2 _type_token)
        _openssl_unquote_token("${_type_token}" _type)
    endif()
    if(_field_count GREATER 3)
        list(GET _fields 3 _count_token)
        _openssl_unquote_token("${_count_token}" _count)
    endif()

    set(${output_var} "${_name}|${_ident}|${_type}|${_count}" PARENT_SCOPE)
endfunction()

function(_openssl_register_decoder_array_definitions expr)
    string(LENGTH "${expr}" _expr_len)
    set(_search_start 0)

    while(_search_start LESS _expr_len)
        math(EXPR _remaining_len "${_expr_len} - ${_search_start}")
        string(SUBSTRING "${expr}" ${_search_start} ${_remaining_len} _tail)
        string(REGEX MATCH "@[A-Za-z_][A-Za-z0-9_]*[ \\t\\r\\n]*=[ \\t\\r\\n]*\\(" _definition_match "${_tail}")
        if(_definition_match STREQUAL "")
            break()
        endif()

        string(FIND "${_tail}" "${_definition_match}" _definition_offset)
        math(EXPR _definition_start "${_search_start} + ${_definition_offset}")
        math(EXPR _definition_tail_len "${_expr_len} - ${_definition_start}")
        string(SUBSTRING "${expr}" ${_definition_start} ${_definition_tail_len} _definition_tail)
        string(REGEX MATCH "^@([A-Za-z_][A-Za-z0-9_]*)[ \\t\\r\\n]*=[ \\t\\r\\n]*\\(" _definition_head "${_definition_tail}")
        set(_array_name "${CMAKE_MATCH_1}")
        string(FIND "${_definition_tail}" "(" _open_paren_offset)
        math(EXPR _open_paren_index "${_definition_start} + ${_open_paren_offset}")
        _openssl_extract_balanced_region("${expr}" ${_open_paren_index} "(" ")" _definition_region _definition_end)
        if(_definition_end EQUAL -1)
            message(FATAL_ERROR "Failed to parse decoder tuple array @${_array_name} in ${INPUT_FILE}")
        endif()

        _openssl_extract_bracket_groups("${_definition_region}" _tuple_groups)
        set(_array_specs)
        foreach(_tuple IN LISTS _tuple_groups)
            _openssl_parse_decoder_tuple("${_tuple}" _spec)
            if(NOT _spec STREQUAL "")
                list(APPEND _array_specs "${_spec}")
            endif()
        endforeach()
        set_property(GLOBAL PROPERTY "_OPENSSL_DECODER_ARRAY_${_array_name}" "${_array_specs}")

        math(EXPR _search_start "${_definition_end} + 1")
    endwhile()
endfunction()

function(_openssl_collect_decoder_specs call_expr output_var)
    set(_specs)

    string(REGEX MATCHALL "@[A-Za-z_][A-Za-z0-9_]*" _array_refs "${call_expr}")
    foreach(_array_ref IN LISTS _array_refs)
        string(REGEX REPLACE "^@([A-Za-z_][A-Za-z0-9_]*)$" "\\1" _ident "${_array_ref}")
        get_property(_array_is_set GLOBAL PROPERTY "_OPENSSL_DECODER_ARRAY_${_ident}" SET)
        if(NOT _array_is_set)
            message(FATAL_ERROR "Unknown decoder tuple array @${_ident} in ${INPUT_FILE}")
        endif()
        get_property(_array_specs GLOBAL PROPERTY "_OPENSSL_DECODER_ARRAY_${_ident}")
        list(APPEND _specs ${_array_specs})
    endforeach()

    _openssl_extract_bracket_groups("${call_expr}" _tuple_groups)
    foreach(_tuple IN LISTS _tuple_groups)
        _openssl_parse_decoder_tuple("${_tuple}" _spec)
        if(NOT _spec STREQUAL "")
            list(APPEND _specs "${_spec}")
        endif()
    endforeach()

    set(${output_var} "${_specs}" PARENT_SCOPE)
endfunction()

function(_openssl_parse_decoder_specs expr output_name output_specs output_with_count)
    if(expr MATCHES "produce_param_decoder_with_count")
        set(_with_count TRUE)
        set(_decoder_macro "produce_param_decoder_with_count")
    else()
        set(_with_count FALSE)
        set(_decoder_macro "produce_param_decoder")
    endif()

    _openssl_register_decoder_array_definitions("${expr}")

    string(FIND "${expr}" "${_decoder_macro}" _call_start)
    if(_call_start EQUAL -1)
        message(FATAL_ERROR "Failed to locate ${_decoder_macro} call in ${INPUT_FILE}: ${expr}")
    endif()
    string(LENGTH "${expr}" _expr_len)
    math(EXPR _call_len "${_expr_len} - ${_call_start}")
    string(SUBSTRING "${expr}" ${_call_start} ${_call_len} _call_expr)

    _openssl_extract_first_quoted_string("${_call_expr}" _decoder_name)
    _openssl_collect_decoder_specs("${_call_expr}" _specs)

    if(_decoder_name STREQUAL "")
        message(FATAL_ERROR "Failed to parse parameter decoder name from ${INPUT_FILE}: ${expr}")
    endif()
    if(NOT _specs)
        message(FATAL_ERROR "Failed to parse parameter decoder specs from ${INPUT_FILE}: ${expr}")
    endif()

    set(${output_name} "${_decoder_name}" PARENT_SCOPE)
    set(${output_specs} "${_specs}" PARENT_SCOPE)
    set(${output_with_count} "${_with_count}" PARENT_SCOPE)
endfunction()

function(_openssl_guard_from_count count_value output_var output_array_len output_hidden)
    set(_guard "")
    set(_array_len "")
    set(_hidden FALSE)
    if(count_value STREQUAL "fips")
        set(_guard "defined(FIPS_MODULE)")
    elseif(count_value STREQUAL "!fips")
        set(_guard "!defined(FIPS_MODULE)")
    elseif(count_value MATCHES "^#if[ \\t]*(.+)$")
        set(_guard "${CMAKE_MATCH_1}")
    elseif(count_value STREQUAL "hidden")
        set(_hidden TRUE)
    elseif(count_value MATCHES "^[0-9]+$")
        set(_array_len "${count_value}")
    elseif(count_value MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        set(_array_len "${count_value}")
    endif()
    set(${output_var} "${_guard}" PARENT_SCOPE)
    set(${output_array_len} "${_array_len}" PARENT_SCOPE)
    set(${output_hidden} "${_hidden}" PARENT_SCOPE)
endfunction()

function(_openssl_generate_param_decoder output_var decoder_name with_count specs)
    set(_text "/* Machine generated by the OpenSSL CMake bootstrap */\n")
    string(APPEND _text "#ifndef ${decoder_name}_list\n")
    string(APPEND _text "static const OSSL_PARAM ${decoder_name}_list[] = {\n")
    foreach(_spec IN LISTS specs)
        string(REPLACE "|" ";" _fields "${_spec}")
        list(GET _fields 0 _name)
        list(GET _fields 1 _ident)
        list(GET _fields 2 _type)
        list(GET _fields 3 _count)
        _openssl_guard_from_count("${_count}" _guard _array_len _hidden)
        if(NOT _ident STREQUAL "invalid param" AND NOT _hidden)
            if(NOT _guard STREQUAL "")
                string(APPEND _text "#if ${_guard}\n")
            endif()
            set(_entry "    OSSL_PARAM_${_type}(${_name}, NULL")
            if(_type STREQUAL "octet_string" OR _type STREQUAL "octet_ptr" OR _type STREQUAL "utf8_string" OR _type STREQUAL "utf8_ptr" OR _type STREQUAL "BN")
                string(APPEND _entry ", 0")
            endif()
            string(APPEND _entry "),\n")
            string(APPEND _text "${_entry}")
            if(NOT _guard STREQUAL "")
                string(APPEND _text "#endif\n")
            endif()
        endif()
    endforeach()
    string(APPEND _text "    OSSL_PARAM_END\n};\n#endif\n\n")
    string(APPEND _text "#ifndef ${decoder_name}_st\n")
    string(APPEND _text "struct ${decoder_name}_st {\n")

    set(_seen_idents)
    foreach(_spec IN LISTS specs)
        string(REPLACE "|" ";" _fields "${_spec}")
        list(GET _fields 1 _ident)
        list(GET _fields 3 _count)
        list(FIND _seen_idents "${_ident}" _already_seen)
        if(_ident STREQUAL "invalid param" OR _already_seen GREATER -1)
            continue()
        endif()
        list(APPEND _seen_idents "${_ident}")
        _openssl_guard_from_count("${_count}" _guard _array_len _hidden)
        if(NOT _guard STREQUAL "")
            string(APPEND _text "#if ${_guard}\n")
        endif()
        if(NOT _array_len STREQUAL "")
            string(APPEND _text "    OSSL_PARAM *${_ident}[${_array_len}];\n")
            string(APPEND _text "    int num_${_ident};\n")
        else()
            string(APPEND _text "    OSSL_PARAM *${_ident};\n")
        endif()
        if(NOT _guard STREQUAL "")
            string(APPEND _text "#endif\n")
        endif()
    endforeach()
    string(APPEND _text "};\n#endif\n\n")

    string(APPEND _text "#ifndef ${decoder_name}_decoder\n")
    string(APPEND _text "static int ${decoder_name}_decoder\n")
    if(with_count)
        string(APPEND _text "    (const OSSL_PARAM *p, struct ${decoder_name}_st *r, int *count)\n")
    else()
        string(APPEND _text "    (const OSSL_PARAM *p, struct ${decoder_name}_st *r)\n")
    endif()
    string(APPEND _text "{\n    const char *s;\n\n")
    if(with_count)
        string(APPEND _text "    *count = 0;\n")
    endif()
    string(APPEND _text "    memset(r, 0, sizeof(*r));\n")
    string(APPEND _text "    if (p != NULL)\n")
    string(APPEND _text "        for (; (s = p->key) != NULL; p++) {\n")
    foreach(_spec IN LISTS specs)
        string(REPLACE "|" ";" _fields "${_spec}")
        list(GET _fields 0 _name)
        list(GET _fields 1 _ident)
        list(GET _fields 3 _count)
        _openssl_param_lookup("${_name}" _param_value)
        _openssl_guard_from_count("${_count}" _guard _array_len _hidden)
        if(NOT _guard STREQUAL "")
            string(APPEND _text "#if ${_guard}\n")
        endif()
        string(APPEND _text "            if (strcmp(s, \"${_param_value}\") == 0) {\n")
        if(_ident STREQUAL "invalid param")
            string(APPEND _text "                ERR_raise_data(ERR_LIB_PROV, ERR_R_UNSUPPORTED,\n")
            string(APPEND _text "                               \"param %s is unsupported\", s);\n")
            string(APPEND _text "                return 0;\n")
        elseif(NOT _array_len STREQUAL "")
            string(APPEND _text "                if (ossl_unlikely(r->num_${_ident} >= ${_array_len})) {\n")
            string(APPEND _text "                    ERR_raise_data(ERR_LIB_PROV, PROV_R_TOO_MANY_RECORDS,\n")
            string(APPEND _text "                                   \"param %s present >%d times\", s, ${_array_len});\n")
            string(APPEND _text "                    return 0;\n")
            string(APPEND _text "                }\n")
            if(with_count)
                string(APPEND _text "                ++*count;\n")
            endif()
            string(APPEND _text "                r->${_ident}[r->num_${_ident}++] = (OSSL_PARAM *)p;\n")
            string(APPEND _text "                continue;\n")
        else()
            string(APPEND _text "                if (ossl_unlikely(r->${_ident} != NULL)) {\n")
            string(APPEND _text "                    ERR_raise_data(ERR_LIB_PROV, PROV_R_REPEATED_PARAMETER,\n")
            string(APPEND _text "                                   \"param %s is repeated\", s);\n")
            string(APPEND _text "                    return 0;\n")
            string(APPEND _text "                }\n")
            if(with_count)
                string(APPEND _text "                ++*count;\n")
            endif()
            string(APPEND _text "                r->${_ident} = (OSSL_PARAM *)p;\n")
            string(APPEND _text "                continue;\n")
        endif()
        string(APPEND _text "            }\n")
        if(NOT _guard STREQUAL "")
            string(APPEND _text "#endif\n")
        endif()
    endforeach()
    string(APPEND _text "        }\n")
    string(APPEND _text "    return 1;\n}\n#endif\n/* End of machine generated */")
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_parse_oid_files expr output_var output_mode)
    string(REGEX MATCHALL "'[^']+\\.asn1'" _matches "${expr}")
    set(_files)
    foreach(_match IN LISTS _matches)
        string(REGEX REPLACE "^'([^']+)'$" "\\1" _file "${_match}")
        list(APPEND _files "${_file}")
    endforeach()
    if(expr MATCHES "filter_to_H")
        set(_mode "H")
    else()
        set(_mode "C")
    endif()
    set(${output_var} "${_files}" PARENT_SCOPE)
    set(${output_mode} "${_mode}" PARENT_SCOPE)
endfunction()

function(_openssl_split_whitespace input output_var)
    string(LENGTH "${input}" _input_len)
    set(_tokens)
    set(_current "")

    if(_input_len GREATER 0)
        math(EXPR _last_index "${_input_len} - 1")
        foreach(_index RANGE 0 ${_last_index})
            string(SUBSTRING "${input}" ${_index} 1 _char)
            if(_char STREQUAL " " OR _char STREQUAL "\t")
                if(NOT _current STREQUAL "")
                    list(APPEND _tokens "${_current}")
                    set(_current "")
                endif()
            else()
                string(APPEND _current "${_char}")
            endif()
        endforeach()
    endif()

    if(NOT _current STREQUAL "")
        list(APPEND _tokens "${_current}")
    endif()

    set(${output_var} "${_tokens}" PARENT_SCOPE)
endfunction()

function(_openssl_oid_parse_value value output_nums output_first_name)
    string(REGEX REPLACE "^[ \\t]*\\{[ \\t]*" "" _body "${value}")
    string(REGEX REPLACE "[ \\t]*\\}[ \\t]*$" "" _body "${_body}")
    _openssl_split_whitespace("${_body}" _tokens)
    set(_nums)
    set(_first_name "")
    set(_index 0)
    set(_pending_named_arc "")
    foreach(_token IN LISTS _tokens)
        if(_token STREQUAL "")
            continue()
        endif()

        if(NOT _pending_named_arc STREQUAL "")
            if(_token MATCHES "^\\(([0-9]+)\\)$")
                list(APPEND _nums "${CMAKE_MATCH_1}")
                set(_pending_named_arc "")
                math(EXPR _index "${_index} + 1")
                continue()
            endif()

            message(FATAL_ERROR "Unsupported OID token pair: ${_pending_named_arc} ${_token}")
        endif()

        string(LENGTH "${_token}" _token_len)
        string(FIND "${_token}" "(" _open_paren)
        string(FIND "${_token}" ")" _close_paren REVERSE)
        if(_open_paren GREATER 0 AND _close_paren GREATER ${_open_paren})
            math(EXPR _last_token_index "${_token_len} - 1")
            if(_close_paren EQUAL _last_token_index)
                string(SUBSTRING "${_token}" 0 ${_open_paren} _token_name)
                math(EXPR _num_start "${_open_paren} + 1")
                math(EXPR _num_len "${_close_paren} - ${_num_start}")
                string(SUBSTRING "${_token}" ${_num_start} ${_num_len} _token_number)
                if(_token_name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$" AND _token_number MATCHES "^[0-9]+$")
                    list(APPEND _nums "${_token_number}")
                    math(EXPR _index "${_index} + 1")
                    continue()
                endif()
            endif()
        elseif(_token MATCHES "^[0-9]+$")
            list(APPEND _nums "${_token}")
            math(EXPR _index "${_index} + 1")
            continue()
        elseif(_token MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
            if(_index EQUAL 0)
                set(_first_name "${_token}")
                string(MAKE_C_IDENTIFIER "${_token}" _lookup_ident)
                if(NOT DEFINED _OPENSSL_OID_NUMS_${_lookup_ident})
                    set(_pending_named_arc "${_token}")
                    continue()
                endif()
                list(APPEND _nums ${_OPENSSL_OID_NUMS_${_lookup_ident}})
                math(EXPR _index "${_index} + 1")
                continue()
            else()
                set(_pending_named_arc "${_token}")
                continue()
            endif()
        endif()

        message(FATAL_ERROR "Unsupported OID token: ${_token}")
    endforeach()

    if(NOT _pending_named_arc STREQUAL "")
        message(FATAL_ERROR "Unterminated OID token: ${_pending_named_arc}")
    endif()

    set(${output_nums} "${_nums}" PARENT_SCOPE)
    set(${output_first_name} "${_first_name}" PARENT_SCOPE)
endfunction()

function(_openssl_oid_mark_arc name)
    if(name STREQUAL "")
        return()
    endif()
    string(MAKE_C_IDENTIFIER "${name}" _ident)
    set(_OPENSSL_OID_TYPE_${_ident} "arc" CACHE INTERNAL "")
endfunction()

function(_openssl_oid_register name nums comment)
    string(MAKE_C_IDENTIFIER "${name}" _ident)
    set(_OPENSSL_OID_NUMS_${_ident} "${nums}" CACHE INTERNAL "")
    if(NOT DEFINED _OPENSSL_OID_TYPE_${_ident})
        set(_OPENSSL_OID_TYPE_${_ident} "leaf" CACHE INTERNAL "")
    endif()
    list(APPEND _OPENSSL_OID_ORDER "${name}")
    set(_OPENSSL_OID_ORDER "${_OPENSSL_OID_ORDER}" CACHE INTERNAL "")
    set(_OPENSSL_OID_COMMENT_${_ident} "${comment}" CACHE INTERNAL "")
endfunction()

function(_openssl_encode_base128 number output_var)
    set(_stack)
    set(_value "${number}")
    while(TRUE)
        math(EXPR _byte "${_value} % 128")
        list(INSERT _stack 0 "${_byte}")
        if(_value LESS 128)
            break()
        endif()
        math(EXPR _value "${_value} / 128")
    endwhile()
    list(LENGTH _stack _stack_len)
    if(_stack_len GREATER 1)
        math(EXPR _limit "${_stack_len} - 2")
        foreach(_idx RANGE 0 ${_limit})
            list(GET _stack ${_idx} _current)
            math(EXPR _current "${_current} + 128")
            list(REMOVE_AT _stack ${_idx})
            list(INSERT _stack ${_idx} "${_current}")
        endforeach()
    endif()
    set(${output_var} "${_stack}" PARENT_SCOPE)
endfunction()

function(_openssl_byte_to_hex number output_var)
    set(_hex_digits 0 1 2 3 4 5 6 7 8 9 A B C D E F)
    math(EXPR _high "(${number} / 16) % 16")
    math(EXPR _low "${number} % 16")
    list(GET _hex_digits ${_high} _high_char)
    list(GET _hex_digits ${_low} _low_char)
    set(${output_var} "0x${_high_char}${_low_char}" PARENT_SCOPE)
endfunction()

function(_openssl_generate_oid_output expr output_var)
    set(_OPENSSL_OID_ORDER "" CACHE INTERNAL "")
    _openssl_parse_oid_files("${expr}" _asn_files _mode)

    foreach(_asn_file IN LISTS _asn_files)
        file(STRINGS "${SOURCE_DIR}/${_asn_file}" _lines)
        set(_pending_comment)
        set(_name "")
        set(_accumulating FALSE)
        set(_value_lines)
        foreach(_line IN LISTS _lines)
            string(REGEX REPLACE "--.*$" "" _clean_line "${_line}")
            _openssl_trim("${_clean_line}" _clean_line)
            if(_line MATCHES "^--")
                string(REGEX REPLACE "^-- ?" "" _comment_line "${_line}")
                list(APPEND _pending_comment "${_comment_line}")
                continue()
            endif()
            if(_accumulating)
                list(APPEND _value_lines "${_clean_line}")
                if(_clean_line MATCHES "\\}")
                    string(JOIN " " _value ${_value_lines})
                    _openssl_oid_parse_value("${_value}" _nums _first_name)
                    _openssl_oid_mark_arc("${_first_name}")
                    string(JOIN "\n" _comment ${_pending_comment})
                    _openssl_oid_register("${_name}" "${_nums}" "${_comment}")
                    set(_pending_comment)
                    set(_value_lines)
                    set(_accumulating FALSE)
                    set(_name "")
                endif()
                continue()
            endif()
            if(_clean_line MATCHES "^([a-z][A-Za-z0-9_-]*)[ \\t]+OBJECT[ \\t]+IDENTIFIER[ \\t]*::=[ \\t]*(\\{.*)$")
                set(_name "${CMAKE_MATCH_1}")
                set(_value_lines "${CMAKE_MATCH_2}")
                if(CMAKE_MATCH_2 MATCHES "\\}")
                    string(JOIN " " _value ${_value_lines})
                    _openssl_oid_parse_value("${_value}" _nums _first_name)
                    _openssl_oid_mark_arc("${_first_name}")
                    string(JOIN "\n" _comment ${_pending_comment})
                    _openssl_oid_register("${_name}" "${_nums}" "${_comment}")
                    set(_pending_comment)
                    set(_value_lines)
                    set(_name "")
                else()
                    set(_accumulating TRUE)
                endif()
            endif()
        endforeach()
    endforeach()

    set(_result)
    foreach(_name IN LISTS _OPENSSL_OID_ORDER)
        string(MAKE_C_IDENTIFIER "${_name}" _ident)
        if(NOT _OPENSSL_OID_TYPE_${_ident} STREQUAL "leaf")
            continue()
        endif()
        set(_nums ${_OPENSSL_OID_NUMS_${_ident}})
        list(LENGTH _nums _num_len)
        if(_num_len LESS 2)
            message(FATAL_ERROR "Invalid OID ${_name}")
        endif()
        list(GET _nums 0 _first)
        list(GET _nums 1 _second)
        math(EXPR _first_byte "(${_first} * 40) + ${_second}")
        set(_bytes "${_first_byte}")
        list(REMOVE_AT _nums 0 1)
        foreach(_num IN LISTS _nums)
            _openssl_encode_base128("${_num}" _encoded)
            list(APPEND _bytes ${_encoded})
        endforeach()
        list(LENGTH _bytes _oid_size)
        math(EXPR _c_bytes_size "2 + ${_oid_size}")
        set(_byte_literals)
        foreach(_byte IN LISTS _bytes)
            _openssl_byte_to_hex("${_byte}" _hex)
            list(APPEND _byte_literals "${_hex}")
        endforeach()
        string(JOIN ", " _byte_text ${_byte_literals})
        set(_comment "${_OPENSSL_OID_COMMENT_${_ident}}")
        if(NOT _comment STREQUAL "")
            string(REPLACE "\n" "\n * " _comment_block "${_comment}")
            string(APPEND _result "\n/*\n * ${_comment_block}\n */\n")
        endif()
        if(_mode STREQUAL "H")
            string(APPEND _result "#define DER_OID_V_${_ident} DER_P_OBJECT, ${_oid_size}, ${_byte_text}\n")
            string(APPEND _result "#define DER_OID_SZ_${_ident} ${_c_bytes_size}\n")
            string(APPEND _result "extern const unsigned char ossl_der_oid_${_ident}[DER_OID_SZ_${_ident}];\n")
        else()
            string(APPEND _result "const unsigned char ossl_der_oid_${_ident}[DER_OID_SZ_${_ident}] = {\n")
            string(APPEND _result "    DER_OID_V_${_ident}\n};\n")
        endif()
    endforeach()
    set(${output_var} "${_result}" PARENT_SCOPE)
endfunction()

function(_openssl_generate_apps_configuration output_var)
    set(_text "static const char * const openssl_disabled_protocols[] = {\n\t\"\",\n")
    foreach(_item IN LISTS DISABLED_PROTOCOLS)
        if(NOT _item STREQUAL "")
            string(APPEND _text "\t\"${_item}\",\n")
        endif()
    endforeach()
    string(APPEND _text "};\n\n")
    string(APPEND _text "static const char * const openssl_disabled_algorithms[] = {\n\t\"\",\n")
    foreach(_item IN LISTS DISABLED_ALGORITHMS)
        if(NOT _item STREQUAL "")
            string(APPEND _text "\t\"${_item}\",\n")
        endif()
    endforeach()
    string(APPEND _text "};\n\n")
    string(APPEND _text "static const char * const openssl_disabled_features[] = {\n\t\"\",\n")
    foreach(_item IN LISTS DISABLED_FEATURES)
        if(NOT _item STREQUAL "")
            string(APPEND _text "\t\"${_item}\",\n")
        endif()
    endforeach()
    string(APPEND _text "};")
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_generate_dso_configuration output_var)
    string(TOUPPER "${DSO_SCHEME}" _scheme)
    if(_scheme STREQUAL "")
        set(_scheme "NONE")
    endif()

    if(_scheme STREQUAL "DLFCN")
        set(_macros DSO_DLFCN HAVE_DLFCN_H)
    elseif(_scheme STREQUAL "DLFCN_NO_H")
        set(_macros DSO_DLFCN)
    else()
        set(_macros "DSO_${_scheme}")
    endif()

    set(_text "")
    foreach(_macro IN LISTS _macros)
        string(APPEND _text "# define ${_macro}\n")
    endforeach()
    string(STRIP "${_text}" _text)
    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

function(_openssl_process_expr expr output_var)
    _openssl_trim("${expr}" _expr)
    set(_text "")
    string(FIND "${_expr}" "@autowarntext" _autowarn_pos)
    string(FIND "${_expr}" "/*" _comment_banner_pos)

    if(NOT _autowarn_pos EQUAL -1 AND NOT _comment_banner_pos EQUAL -1)
        set(_text "/* Warning: generated by the OpenSSL CMake bootstrap. */\n/* Do not edit this file directly. */")
    elseif(NOT _autowarn_pos EQUAL -1)
        set(_text "Warning: generated by the OpenSSL CMake bootstrap.\n * Do not edit this file directly.")
    elseif(_expr MATCHES "^use OpenSSL::")
        set(_text "")
    elseif(_expr MATCHES "generate_public_macros\\(\\)")
        _openssl_generate_public_macros(_text)
    elseif(_expr MATCHES "produce_param_decoder")
        _openssl_parse_decoder_specs("${_expr}" _decoder_name _decoder_specs _with_count)
        _openssl_generate_param_decoder(_text "${_decoder_name}" ${_with_count} "${_decoder_specs}")
    elseif(_expr MATCHES "oids_to_c::process_leaves")
        _openssl_generate_oid_output("${_expr}" _text)
    elseif(_expr MATCHES "generate_openssl_disable_array")
        _openssl_generate_apps_configuration(_text)
    elseif(_expr MATCHES "dso_scheme" AND _expr MATCHES "DSO_" AND _expr MATCHES "macros")
        _openssl_generate_dso_configuration(_text)
    elseif(_expr MATCHES "openssl_sys_defines" AND _expr MATCHES "openssl_feature_defines")
        foreach(_define IN LISTS SYS_DEFINES)
            if(NOT _define STREQUAL "")
                string(APPEND _text "# ifndef ${_define}\n#  define ${_define} 1\n# endif\n")
            endif()
        endforeach()
        foreach(_define IN LISTS API_DEFINES)
            if(NOT _define STREQUAL "")
                if(_define MATCHES "^([^=]+)=(.*)$")
                    string(APPEND _text "# define ${CMAKE_MATCH_1} ${CMAKE_MATCH_2}\n")
                else()
                    string(APPEND _text "# define ${_define}\n")
                endif()
            endif()
        endforeach()
        foreach(_define IN LISTS FEATURE_DEFINES)
            if(NOT _define STREQUAL "")
                string(APPEND _text "# ifndef ${_define}\n#  define ${_define}\n# endif\n")
            endif()
        endforeach()
    elseif(_expr MATCHES "\\$config\\{processor\\}" AND _expr MATCHES "386" AND _expr MATCHES "# define" AND _expr MATCHES "# undef")
        if(PROCESSOR STREQUAL "386")
            set(_text "# define")
        else()
            set(_text "# undef")
        endif()
    elseif(_expr MATCHES "\\$config\\{bn_ll\\}" AND _expr MATCHES "#  define" AND _expr MATCHES "#  undef")
        if(POINTER_MODEL STREQUAL "BN_LLONG")
            set(_text "#  define")
        else()
            set(_text "#  undef")
        endif()
    elseif(_expr MATCHES "\\$config\\{b64l\\}" AND _expr MATCHES "#  define" AND _expr MATCHES "#  undef")
        if(POINTER_MODEL STREQUAL "SIXTY_FOUR_BIT_LONG")
            set(_text "#  define")
        else()
            set(_text "#  undef")
        endif()
    elseif(_expr MATCHES "\\$config\\{b64\\}" AND _expr MATCHES "#  define" AND _expr MATCHES "#  undef")
        if(POINTER_MODEL STREQUAL "SIXTY_FOUR_BIT")
            set(_text "#  define")
        else()
            set(_text "#  undef")
        endif()
    elseif(_expr MATCHES "\\$config\\{b32\\}" AND _expr MATCHES "#  define" AND _expr MATCHES "#  undef")
        if(POINTER_MODEL STREQUAL "THIRTY_TWO_BIT")
            set(_text "#  define")
        else()
            set(_text "#  undef")
        endif()
    elseif(_expr MATCHES "^\\$config\\{rc4_int\\}$")
        set(_text "${RC4_INT}")
    elseif(_expr MATCHES "^join\\(', ', map \{ \"0x\\\$_\" \} unpack\\(\"\\(A2\\)\\*\", \\$config\\{FIPSKEY\\}\\)\\)$")
        set(_text "0x00")
    elseif(_expr MATCHES "platform->dsoext\\(\\)")
        set(_text "${DSO_EXTENSION}")
    else()
        string(REGEX MATCHALL "generate_stack_macros\\(\"[^\"]+\"\\)|generate_const_stack_macros\\(\"[^\"]+\"\\)|generate_lhash_macros\\(\"[^\"]+\"\\)|generate_stack_string_macros\\(\\)|generate_stack_const_string_macros\\(\\)|generate_stack_block_macros\\(\\)" _stack_calls "${_expr}")
        if(_stack_calls)
            foreach(_call IN LISTS _stack_calls)
                if(_call MATCHES "^generate_stack_macros\\(\"([^\"]+)\"\\)$")
                    _openssl_stack_macros(_fragment "${CMAKE_MATCH_1}" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_1}")
                elseif(_call MATCHES "^generate_const_stack_macros\\(\"([^\"]+)\"\\)$")
                    _openssl_stack_macros(_fragment "${CMAKE_MATCH_1}" "const ${CMAKE_MATCH_1}" "${CMAKE_MATCH_1}")
                elseif(_call MATCHES "^generate_lhash_macros\\(\"([^\"]+)\"\\)$")
                    _openssl_lhash_macros(_fragment "${CMAKE_MATCH_1}")
                elseif(_call MATCHES "^generate_stack_string_macros\\(\\)$")
                    _openssl_stack_macros(_fragment "OPENSSL_STRING" "char" "char")
                elseif(_call MATCHES "^generate_stack_const_string_macros\\(\\)$")
                    _openssl_stack_macros(_fragment "OPENSSL_CSTRING" "const char" "char")
                elseif(_call MATCHES "^generate_stack_block_macros\\(\\)$")
                    _openssl_stack_macros(_fragment "OPENSSL_BLOCK" "void" "void")
                endif()
                if(NOT _text STREQUAL "")
                    string(APPEND _text "\n")
                endif()
                string(APPEND _text "${_fragment}")
            endforeach()
        else()
            set(_generic "${_expr}")
            while(_generic MATCHES "\\$config\\{([A-Za-z0-9_]+)\\}")
                set(_key "${CMAKE_MATCH_1}")
                _openssl_get_config_value("${_key}" _value)
                set(_placeholder "\$config{${_key}}")
                string(REPLACE "${_placeholder}" "${_value}" _generic "${_generic}")
            endwhile()
            if(_generic MATCHES "^\"(.*)\"$")
                set(_text "${CMAKE_MATCH_1}")
            else()
                set(_text "${_generic}")
            endif()
        endif()
    endif()

    set(${output_var} "${_text}" PARENT_SCOPE)
endfunction()

file(READ "${INPUT_FILE}" _input_text)
set(_output_text "")
set(_remaining_text "${_input_text}")

while(TRUE)
    string(FIND "${_remaining_text}" "{-" _start)
    if(_start EQUAL -1)
        string(APPEND _output_text "${_remaining_text}")
        break()
    endif()

    string(SUBSTRING "${_remaining_text}" 0 ${_start} _before)
    string(APPEND _output_text "${_before}")

    math(EXPR _expr_offset "${_start} + 2")
    string(SUBSTRING "${_remaining_text}" ${_expr_offset} -1 _after_start)
    string(FIND "${_after_start}" "-}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Unterminated template expression in ${INPUT_FILE}")
    endif()

    string(SUBSTRING "${_after_start}" 0 ${_end} _expr)
    math(EXPR _remaining_offset "${_end} + 2")
    string(SUBSTRING "${_after_start}" ${_remaining_offset} -1 _remaining_text)

    _openssl_process_expr("${_expr}" _replacement)
    string(APPEND _output_text "${_replacement}")
endwhile()

get_filename_component(_output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
file(WRITE "${OUTPUT_FILE}" "${_output_text}")