include_guard(GLOBAL)

include(FetchContent)

set(FETCHCONTENT_QUIET ON)

function(_openssl_cmake_make_interface_target target_name)
    if(NOT TARGET ${target_name})
        add_library(${target_name} INTERFACE)
    endif()
endfunction()

function(openssl_cmake_resolve_zlib source_dir)
    if(NOT OPENSSL_CMAKE_ENABLE_ZLIB AND NOT OPENSSL_CMAKE_ENABLE_ZLIB_DYNAMIC)
        set(OPENSSL_CMAKE_ZLIB_ACTIVE OFF PARENT_SCOPE)
        set(OPENSSL_CMAKE_ZLIB_TARGET "" PARENT_SCOPE)
        set(OPENSSL_CMAKE_ZLIB_ORIGIN "OFF" PARENT_SCOPE)
        return()
    endif()

    set(_origin "")
    set(_target "")

    if(NOT OPENSSL_CMAKE_ZLIB_INCLUDE_DIR STREQUAL "" OR NOT OPENSSL_CMAKE_ZLIB_LIBRARY STREQUAL "")
        if(OPENSSL_CMAKE_ZLIB_INCLUDE_DIR STREQUAL "")
            message(FATAL_ERROR "OPENSSL_CMAKE_ZLIB_INCLUDE_DIR is required when OPENSSL_CMAKE_ZLIB_LIBRARY is set.")
        endif()

        _openssl_cmake_make_interface_target(openssl_cmake_zlib_headers)
        target_include_directories(openssl_cmake_zlib_headers INTERFACE "${OPENSSL_CMAKE_ZLIB_INCLUDE_DIR}")

        if(OPENSSL_CMAKE_ENABLE_ZLIB)
            set(_library_path "${OPENSSL_CMAKE_ZLIB_LIBRARY}")
            if(_library_path STREQUAL "")
                message(FATAL_ERROR "OPENSSL_CMAKE_ZLIB_LIBRARY is required when OPENSSL_CMAKE_ENABLE_ZLIB is ON.")
            endif()
            if(IS_DIRECTORY "${_library_path}")
                find_library(_zlib_user_library NAMES z zlib zlibstatic zlib1 HINTS "${_library_path}" NO_DEFAULT_PATH)
                if(NOT _zlib_user_library)
                    message(FATAL_ERROR "Failed to find a zlib library in ${_library_path}.")
                endif()
                set(_library_path "${_zlib_user_library}")
            endif()
            if(NOT TARGET openssl_cmake_zlib)
                add_library(openssl_cmake_zlib UNKNOWN IMPORTED)
            endif()
            set_target_properties(openssl_cmake_zlib PROPERTIES
                IMPORTED_LOCATION "${_library_path}"
                INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_CMAKE_ZLIB_INCLUDE_DIR}"
            )
            set(_target openssl_cmake_zlib)
        else()
            set(_target openssl_cmake_zlib_headers)
        endif()
        set(_origin "custom")
    elseif(OPENSSL_CMAKE_DEPS STREQUAL "LOCAL")
        find_package(ZLIB REQUIRED)
        if(OPENSSL_CMAKE_ENABLE_ZLIB)
            set(_target ZLIB::ZLIB)
        else()
            get_target_property(_zlib_include_dirs ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES)
            _openssl_cmake_make_interface_target(openssl_cmake_zlib_headers)
            target_include_directories(openssl_cmake_zlib_headers INTERFACE ${_zlib_include_dirs})
            set(_target openssl_cmake_zlib_headers)
        endif()
        set(_origin "system")
    else()
        if(IS_DIRECTORY "${source_dir}/deps/zlib")
            set(FETCHCONTENT_SOURCE_DIR_ZLIB "${source_dir}/deps/zlib")
            set(_origin "bundled")
        endif()

        if(OPENSSL_CMAKE_ENABLE_ZLIB)
            if(OPENSSL_CMAKE_DEPS STREQUAL "AUTO" AND NOT DEFINED FETCHCONTENT_SOURCE_DIR_ZLIB AND FETCHCONTENT_FULLY_DISCONNECTED)
                find_package(ZLIB QUIET)
                if(ZLIB_FOUND)
                    set(_target ZLIB::ZLIB)
                    set(_origin "system")
                endif()
            endif()

            if(_target STREQUAL "")
                set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
                set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
                set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
                set(ZLIB_INSTALL OFF CACHE BOOL "" FORCE)
                FetchContent_Declare(
                    zlib
                    URL https://github.com/madler/zlib/archive/refs/tags/v1.3.2.tar.gz
                    URL_HASH SHA256=b99a0b86c0ba9360ec7e78c4f1e43b1cbdf1e6936c8fa0f6835c0cd694a495a1
                    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
                )
                FetchContent_MakeAvailable(zlib)
                if(TARGET ZLIB::ZLIBSTATIC)
                    set(_target ZLIB::ZLIBSTATIC)
                elseif(TARGET zlibstatic)
                    set(_target zlibstatic)
                else()
                    message(FATAL_ERROR "Fetched zlib but could not find a static zlib target.")
                endif()
                if(_origin STREQUAL "")
                    set(_origin "downloaded")
                endif()
            endif()
        else()
            if(OPENSSL_CMAKE_DEPS STREQUAL "AUTO" AND NOT DEFINED FETCHCONTENT_SOURCE_DIR_ZLIB AND FETCHCONTENT_FULLY_DISCONNECTED)
                find_package(ZLIB QUIET)
                if(ZLIB_FOUND)
                    get_target_property(_zlib_include_dirs ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES)
                    _openssl_cmake_make_interface_target(openssl_cmake_zlib_headers)
                    target_include_directories(openssl_cmake_zlib_headers INTERFACE ${_zlib_include_dirs})
                    set(_target openssl_cmake_zlib_headers)
                    set(_origin "system")
                endif()
            endif()

            if(_target STREQUAL "")
                set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
                set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
                set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
                set(ZLIB_INSTALL OFF CACHE BOOL "" FORCE)
                FetchContent_Declare(
                    zlib
                    URL https://github.com/madler/zlib/archive/refs/tags/v1.3.2.tar.gz
                    URL_HASH SHA256=b99a0b86c0ba9360ec7e78c4f1e43b1cbdf1e6936c8fa0f6835c0cd694a495a1
                    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
                )
                FetchContent_MakeAvailable(zlib)
                if(TARGET zlibstatic)
                    get_target_property(_zlib_include_dirs zlibstatic INTERFACE_INCLUDE_DIRECTORIES)
                elseif(TARGET zlib)
                    get_target_property(_zlib_include_dirs zlib INTERFACE_INCLUDE_DIRECTORIES)
                else()
                    message(FATAL_ERROR "Fetched zlib but could not determine zlib include directories.")
                endif()
                _openssl_cmake_make_interface_target(openssl_cmake_zlib_headers)
                target_include_directories(openssl_cmake_zlib_headers INTERFACE ${_zlib_include_dirs})
                set(_target openssl_cmake_zlib_headers)
                if(_origin STREQUAL "")
                    set(_origin "downloaded")
                endif()
            endif()
        endif()
    endif()

    set(OPENSSL_CMAKE_ZLIB_ACTIVE ON PARENT_SCOPE)
    set(OPENSSL_CMAKE_ZLIB_TARGET "${_target}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_ZLIB_ORIGIN "${_origin}" PARENT_SCOPE)
endfunction()

function(openssl_cmake_resolve_jitter source_dir)
    if(NOT OPENSSL_CMAKE_ENABLE_JITTER)
        set(OPENSSL_CMAKE_JITTER_TARGET "" PARENT_SCOPE)
        set(OPENSSL_CMAKE_JITTER_ORIGIN "OFF" PARENT_SCOPE)
        return()
    endif()

    set(_origin "")
    set(_target "")

    if(NOT OPENSSL_CMAKE_JITTER_INCLUDE_DIR STREQUAL "" OR NOT OPENSSL_CMAKE_JITTER_LIBRARY STREQUAL "")
        if(OPENSSL_CMAKE_JITTER_INCLUDE_DIR STREQUAL "")
            message(FATAL_ERROR "OPENSSL_CMAKE_JITTER_INCLUDE_DIR is required when OPENSSL_CMAKE_JITTER_LIBRARY is set.")
        endif()
        set(_library_path "${OPENSSL_CMAKE_JITTER_LIBRARY}")
        if(_library_path STREQUAL "")
            message(FATAL_ERROR "OPENSSL_CMAKE_JITTER_LIBRARY is required when OPENSSL_CMAKE_ENABLE_JITTER is ON with custom paths.")
        endif()
        if(IS_DIRECTORY "${_library_path}")
            find_library(_jitter_user_library NAMES jitterentropy libjitterentropy HINTS "${_library_path}" NO_DEFAULT_PATH)
            if(NOT _jitter_user_library)
                message(FATAL_ERROR "Failed to find a jitterentropy library in ${_library_path}.")
            endif()
            set(_library_path "${_jitter_user_library}")
        endif()
        if(NOT TARGET openssl_cmake_jitterentropy)
            add_library(openssl_cmake_jitterentropy UNKNOWN IMPORTED)
        endif()
        set_target_properties(openssl_cmake_jitterentropy PROPERTIES
            IMPORTED_LOCATION "${_library_path}"
            INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_CMAKE_JITTER_INCLUDE_DIR}"
        )
        set(_target openssl_cmake_jitterentropy)
        set(_origin "custom")
    elseif(OPENSSL_CMAKE_DEPS STREQUAL "LOCAL")
        find_path(_jitter_include_dir NAMES jitterentropy.h PATH_SUFFIXES include)
        find_library(_jitter_library NAMES jitterentropy libjitterentropy)
        if(NOT _jitter_include_dir OR NOT _jitter_library)
            message(FATAL_ERROR "Failed to find jitterentropy headers and library in LOCAL mode.")
        endif()
        if(NOT TARGET openssl_cmake_jitterentropy)
            add_library(openssl_cmake_jitterentropy UNKNOWN IMPORTED)
        endif()
        set_target_properties(openssl_cmake_jitterentropy PROPERTIES
            IMPORTED_LOCATION "${_jitter_library}"
            INTERFACE_INCLUDE_DIRECTORIES "${_jitter_include_dir}"
        )
        set(_target openssl_cmake_jitterentropy)
        set(_origin "system")
    else()
        if(IS_DIRECTORY "${source_dir}/deps/jitterentropy-library")
            set(FETCHCONTENT_SOURCE_DIR_JITTERENTROPY "${source_dir}/deps/jitterentropy-library")
            set(_origin "bundled")
        elseif(IS_DIRECTORY "${source_dir}/deps/jitterentropy")
            set(FETCHCONTENT_SOURCE_DIR_JITTERENTROPY "${source_dir}/deps/jitterentropy")
            set(_origin "bundled")
        endif()

        FetchContent_Declare(
            jitterentropy
            URL https://github.com/smuellerDD/jitterentropy-library/archive/refs/tags/v3.6.3.tar.gz
            URL_HASH SHA256=50d6a6a3e12c05ff8200e51afde7aa04453e6503e31c41554ed577733d10fb72
            DOWNLOAD_EXTRACT_TIMESTAMP TRUE
        )
        FetchContent_GetProperties(jitterentropy)
        if(NOT jitterentropy_POPULATED)
            FetchContent_Populate(jitterentropy)
        endif()

        file(GLOB _jitter_sources CONFIGURE_DEPENDS "${jitterentropy_SOURCE_DIR}/src/*.c")
        if(NOT TARGET openssl_cmake_jitterentropy)
            add_library(openssl_cmake_jitterentropy STATIC ${_jitter_sources})
            target_include_directories(openssl_cmake_jitterentropy PUBLIC
                "${jitterentropy_SOURCE_DIR}"
                "${jitterentropy_SOURCE_DIR}/arch"
                "${jitterentropy_SOURCE_DIR}/src"
            )
            set_target_properties(openssl_cmake_jitterentropy PROPERTIES POSITION_INDEPENDENT_CODE ON)
            if(TARGET Threads::Threads)
                target_link_libraries(openssl_cmake_jitterentropy PUBLIC Threads::Threads)
            endif()
        endif()
        set(_target openssl_cmake_jitterentropy)
        if(_origin STREQUAL "")
            set(_origin "downloaded")
        endif()
    endif()

    set(OPENSSL_CMAKE_JITTER_TARGET "${_target}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_JITTER_ORIGIN "${_origin}" PARENT_SCOPE)
endfunction()