function(openssl_cmake_load_version version_file out_major out_minor out_patch out_prerelease out_build_metadata out_release_date)
    if(NOT EXISTS "${version_file}")
        message(FATAL_ERROR "VERSION file not found: ${version_file}")
    endif()

    file(STRINGS "${version_file}" _version_lines)

    unset(_major)
    unset(_minor)
    unset(_patch)
    unset(_prerelease)
    unset(_build_metadata)
    unset(_release_date)

    foreach(_line IN LISTS _version_lines)
        if(_line MATCHES "^MAJOR=([0-9]+)$")
            set(_major "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^MINOR=([0-9]+)$")
            set(_minor "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^PATCH=([0-9]+)$")
            set(_patch "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^PRE_RELEASE_TAG=(.*)$")
            if(CMAKE_MATCH_1 STREQUAL "")
                set(_prerelease "")
            else()
                set(_prerelease "-${CMAKE_MATCH_1}")
            endif()
        elseif(_line MATCHES "^BUILD_METADATA=(.*)$")
            set(_build_metadata "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^RELEASE_DATE=(.*)$")
            set(_release_date "${CMAKE_MATCH_1}")
            if(_release_date MATCHES "^\"(.*)\"$")
                set(_release_date "${CMAKE_MATCH_1}")
            endif()
        endif()
    endforeach()

    if(NOT DEFINED _major OR NOT DEFINED _minor OR NOT DEFINED _patch)
        message(FATAL_ERROR "Failed to parse version components from ${version_file}")
    endif()

    set(${out_major} "${_major}" PARENT_SCOPE)
    set(${out_minor} "${_minor}" PARENT_SCOPE)
    set(${out_patch} "${_patch}" PARENT_SCOPE)
    set(${out_prerelease} "${_prerelease}" PARENT_SCOPE)
    set(${out_build_metadata} "${_build_metadata}" PARENT_SCOPE)
    set(${out_release_date} "${_release_date}" PARENT_SCOPE)
endfunction()

function(openssl_cmake_detect_target out_target)
    if(WIN32)
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|amd64|x86_64)$")
            set(_target "mingw64")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
            set(_target "mingwarm64")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86|i.86)$")
            set(_target "mingw")
        else()
            message(FATAL_ERROR "Unsupported Windows processor for this bootstrap: ${CMAKE_SYSTEM_PROCESSOR}")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(_target "linux-x86_64")
        else()
            set(_target "linux-x86")
        endif()
    else()
        message(FATAL_ERROR "Unsupported platform for this bootstrap: ${CMAKE_SYSTEM_NAME}")
    endif()

    set(${out_target} "${_target}" PARENT_SCOPE)
endfunction()

function(openssl_cmake_configure_target)
    set(_options)
    set(_one_value TARGET_NAME ENABLE_THREADS ENABLE_ZLIB ENABLE_ZLIB_DYNAMIC ENABLE_MODULES)
    set(_multi_value)
    cmake_parse_arguments(OSSL_CFG "${_options}" "${_one_value}" "${_multi_value}" ${ARGN})

    if(NOT OSSL_CFG_TARGET_NAME)
        message(FATAL_ERROR "openssl_cmake_configure_target requires TARGET_NAME")
    endif()

    set(OPENSSL_CMAKE_DSO_EXTENSION ".so" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DSO_SCHEME "dlfcn" PARENT_SCOPE)
    set(OPENSSL_CMAKE_SHARED_SYSTEM_LIBS "" PARENT_SCOPE)
    set(OPENSSL_CMAKE_SHARED_LINK_OPTIONS "" PARENT_SCOPE)
    set(OPENSSL_CMAKE_OS_DEFINES "" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DISABLED_PROTOCOLS "" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DISABLED_ALGORITHMS "" PARENT_SCOPE)

    if(OSSL_CFG_TARGET_NAME STREQUAL "mingw")
        set(_sys_defines "OPENSSL_SYS_WIN32")
        set(_shared_libs "ws2_32;gdi32;crypt32")
        set(_shared_link_options "-static-libgcc")
        set(_dso ".dll")
        set(_dso_scheme "win32")
        set(_processor "386")
        set(_pointer_model "BN_LLONG")
    elseif(OSSL_CFG_TARGET_NAME STREQUAL "mingw64")
        set(_sys_defines "OPENSSL_SYS_WIN32")
        set(_shared_libs "ws2_32;gdi32;crypt32")
        set(_shared_link_options "-static-libgcc")
        set(_dso ".dll")
        set(_dso_scheme "win32")
        set(_processor "x86_64")
        set(_pointer_model "SIXTY_FOUR_BIT")
    elseif(OSSL_CFG_TARGET_NAME STREQUAL "mingwarm64")
        set(_sys_defines "OPENSSL_SYS_WIN32")
        set(_shared_libs "ws2_32;gdi32;crypt32")
        set(_shared_link_options "-static-libgcc")
        set(_dso ".dll")
        set(_dso_scheme "win32")
        set(_processor "aarch64")
        set(_pointer_model "SIXTY_FOUR_BIT")
    elseif(OSSL_CFG_TARGET_NAME MATCHES "^linux-")
        set(_sys_defines "")
        set(_shared_libs "dl")
        set(_shared_link_options "")
        set(_dso ".so")
        set(_dso_scheme "dlfcn")
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(_processor "x86_64")
            set(_pointer_model "SIXTY_FOUR_BIT_LONG")
        else()
            set(_processor "386")
            set(_pointer_model "THIRTY_TWO_BIT")
        endif()
    else()
        message(FATAL_ERROR "Unknown bootstrap target: ${OSSL_CFG_TARGET_NAME}")
    endif()

    if(OSSL_CFG_ENABLE_THREADS)
        list(APPEND _shared_libs pthread)
        set(_os_defines "OPENSSL_THREADS;${_sys_defines}")
    else()
        set(_os_defines "${_sys_defines}")
    endif()

    set(OPENSSL_CMAKE_DSO_EXTENSION "${_dso}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DSO_SCHEME "${_dso_scheme}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_SHARED_SYSTEM_LIBS "${_shared_libs}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_SHARED_LINK_OPTIONS "${_shared_link_options}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_OS_DEFINES "${_os_defines}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_PROCESSOR "${_processor}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_POINTER_MODEL "${_pointer_model}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_RC4_INT "unsigned int" PARENT_SCOPE)

    set(_disabled_features "asm;fips")
    set(_openssl_feature_defines "OPENSSL_NO_ASM;OPENSSL_NO_FIPS")
    set(_openssl_api_defines "")
    set(_disabled_algorithms "")

    if(NOT OSSL_CFG_ENABLE_MODULES)
        list(APPEND _disabled_features module)
        list(APPEND _openssl_feature_defines OPENSSL_NO_MODULE)
    endif()

    if(NOT OSSL_CFG_ENABLE_THREADS)
        list(APPEND _openssl_feature_defines OPENSSL_NO_THREADS)
    endif()

    if(NOT OSSL_CFG_ENABLE_ZLIB AND NOT OSSL_CFG_ENABLE_ZLIB_DYNAMIC)
        list(APPEND _openssl_feature_defines OPENSSL_NO_ZLIB)
        list(APPEND _disabled_algorithms zlib)
    endif()

    set(OPENSSL_CMAKE_OPENSSL_SYS_DEFINES "${_sys_defines}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_OPENSSL_API_DEFINES "${_openssl_api_defines}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_OPENSSL_FEATURE_DEFINES "${_openssl_feature_defines}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DISABLED_FEATURES "${_disabled_features}" PARENT_SCOPE)
    set(OPENSSL_CMAKE_DISABLED_ALGORITHMS "${_disabled_algorithms}" PARENT_SCOPE)
endfunction()
